# Starter pipeline

trigger:
- serverless/reference

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AmazonWebServices.aws-vsts-tools.LambdaNETCoreDeploy.LambdaNETCoreDeploy@1
  displayName: 'Deploy .NET Core to Lambda:  '
  inputs:
    awsCredentials: default
    regionName: 'us-east-1'
    command: deployServerless
    lambdaProjectPath: src/DotNetServerless